
import React, { useState, useEffect } from 'react';
import { Patient } from '../../types';
import { ICONS, MOCK_PATIENTS } from '../../constants';

interface DocumentationViewProps {
  initialPatient: Patient | null;
  externalDraft?: any;
  onClearDraft: () => void;
}

const DocumentationView: React.FC<DocumentationViewProps> = ({ initialPatient, externalDraft, onClearDraft }) => {
  const [selectedPatient, setSelectedPatient] = useState<Patient | null>(initialPatient);
  const [noteType, setNoteType] = useState('SOAP Note');
  const [sections, setSections] = useState({
    subjective: '',
    objective: '',
    assessment: '',
    plan: ''
  });
  const [isDrafting, setIsDrafting] = useState(false);

  // Sync with external draft if Bianca sends one
  useEffect(() => {
    if (externalDraft) {
      setSections({
        subjective: externalDraft.sections.chief_complaint || '',
        objective: externalDraft.sections.history || '', // Mapping logic for mock demo
        assessment: externalDraft.sections.assessment || '',
        plan: externalDraft.sections.plan || ''
      });
      // Optionally pre-select patient if not already
      if (!selectedPatient) {
        setSelectedPatient(MOCK_PATIENTS[0]);
      }
    }
  }, [externalDraft]);

  const handleBiancaDraft = () => {
    setIsDrafting(true);
    // Simulate internal AI drafting
    setTimeout(() => {
      setSections({
        subjective: "Patient reports mild discomfort in left knee for 3 days. No swelling observed.",
        objective: "Range of motion limited to 110 degrees. No warmth or redness.",
        assessment: "Minor muscular strain suspected, possibly overuse.",
        plan: "RICE protocol. Follow up in 7 days if symptoms persist."
      });
      setIsDrafting(false);
    }, 1500);
  };

  return (
    <div className="max-w-5xl mx-auto space-y-6 animate-in fade-in duration-500">
       <header className="flex items-center justify-between">
         <div>
          <h1 className="text-3xl font-bold text-slate-900">Documentation</h1>
          <p className="text-slate-500 mt-1">SOAP, Intake, and Visit Summary Workspace.</p>
         </div>
         <div className="flex gap-2">
            <button className="px-4 py-2 bg-white border border-slate-200 rounded-xl text-sm font-bold text-slate-700">Save Draft</button>
            <button className="px-4 py-2 bg-blue-600 text-white rounded-xl text-sm font-bold shadow-lg shadow-blue-500/20">Sign & Approve</button>
         </div>
       </header>

       {externalDraft && (
         <div className="bg-amber-50 border border-amber-200 p-4 rounded-xl flex items-center justify-between animate-in slide-in-from-top-4">
           <div className="flex items-center gap-3">
             <ICONS.AlertTriangle className="text-amber-600" size={20} />
             <div>
               <p className="text-sm font-bold text-amber-800">DRAFT — Requires Human Review</p>
               <p className="text-xs text-amber-700">This content was generated by Bianca AI. Please verify all clinical facts.</p>
             </div>
           </div>
           {/* Fixed: Replaced missing setExternalDraft with onClearDraft callback from props */}
           <button 
            onClick={onClearDraft}
            className="text-xs font-bold text-amber-900 hover:underline"
           >
             Dismiss Banner
           </button>
         </div>
       )}

       <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
         <div className="lg:col-span-2 space-y-6">
            <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm space-y-4">
               <div className="flex gap-4 mb-4">
                 <div className="flex-1">
                   <label className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block mb-1">Select Patient</label>
                   <select 
                    value={selectedPatient?.id || ''}
                    onChange={(e) => setSelectedPatient(MOCK_PATIENTS.find(p => p.id === e.target.value) || null)}
                    className="w-full p-2 bg-slate-50 border border-slate-200 rounded-lg text-sm"
                   >
                     <option value="">Search Patients...</option>
                     {MOCK_PATIENTS.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}
                   </select>
                 </div>
                 <div className="flex-1">
                   <label className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block mb-1">Note Type</label>
                   <select 
                    value={noteType}
                    onChange={(e) => setNoteType(e.target.value)}
                    className="w-full p-2 bg-slate-50 border border-slate-200 rounded-lg text-sm"
                   >
                     <option>SOAP Note</option>
                     <option>Intake Assessment</option>
                     <option>Discharge Summary</option>
                   </select>
                 </div>
               </div>

               {Object.entries(sections).map(([key, val]) => (
                 <div key={key}>
                   <label className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block mb-1 capitalize">{key}</label>
                   <textarea 
                    value={val}
                    onChange={(e) => setSections({...sections, [key]: e.target.value})}
                    placeholder={`Enter ${key} findings...`}
                    rows={4}
                    className="w-full p-3 bg-white border border-slate-200 rounded-xl text-sm focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 transition-all outline-none"
                   />
                 </div>
               ))}
            </div>

            <div className="bg-blue-600/5 border border-blue-600/20 p-4 rounded-xl flex items-center justify-between">
              <div className="flex items-center gap-3">
                <ICONS.ShieldCheck className="text-blue-600" size={20} />
                <span className="text-sm font-bold text-blue-800">
                  Author Chain: Bianca AI &rarr; {selectedPatient ? 'In Review' : 'Draft'}
                </span>
              </div>
              <span className="text-[10px] font-bold text-blue-400 uppercase tracking-widest">Awaiting Verification</span>
            </div>
         </div>

         <div className="space-y-6">
            <button 
              onClick={handleBiancaDraft}
              disabled={isDrafting}
              className="w-full p-6 bg-gradient-to-br from-blue-600 to-indigo-700 text-white rounded-3xl shadow-xl hover:shadow-2xl transition-all group overflow-hidden relative"
            >
              <div className="relative z-10 flex flex-col items-center gap-3">
                 <div className={`p-3 bg-white/20 rounded-full backdrop-blur-md ${isDrafting ? 'animate-spin' : 'group-hover:scale-110 transition-transform'}`}>
                   <ICONS.Sparkles size={32} />
                 </div>
                 <div className="text-center">
                    <h3 className="font-bold text-lg">Bianca Draft Assist</h3>
                    <p className="text-blue-100 text-xs mt-1">Auto-complete clinical notes based on patient history.</p>
                 </div>
              </div>
            </button>

            <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm">
               <h3 className="font-bold text-slate-800 text-sm mb-4">Documentation Checklist</h3>
               <div className="space-y-4">
                  {[
                    { label: 'Verify identity', done: true },
                    { label: 'Document vitals', done: false },
                    { label: 'Check drug interactions', done: false },
                    { label: 'Sign & Finalize', done: false },
                  ].map((item, i) => (
                    <div key={i} className="flex items-center gap-3">
                       <div className={`w-5 h-5 rounded-full border flex items-center justify-center ${item.done ? 'bg-emerald-500 border-emerald-500 text-white' : 'border-slate-300'}`}>
                         {item.done && <ICONS.CheckCircle size={14} />}
                       </div>
                       <p className="text-xs font-medium text-slate-600">{item.label}</p>
                    </div>
                  ))}
               </div>
            </div>
         </div>
       </div>
    </div>
  );
};

export default DocumentationView;
