// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { DEMO_MODE } from "@/lib/demo-mode";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

type SupabaseClientLike = ReturnType<typeof createClient<Database>> | {
  auth: {
    getSession: () => Promise<{ data: { session: null }, error: null }>;
    onAuthStateChange: () => { data: { subscription: { unsubscribe: () => void } } };
  };
  from: () => {
    select: () => any;
    insert: () => any;
    update: () => any;
  };
};

const mockSupabase: SupabaseClientLike = {
  auth: {
    getSession: async () => ({ data: { session: null }, error: null }),
    onAuthStateChange: () => ({
      data: { subscription: { unsubscribe: () => {} } },
    }),
  },
  from: () => ({
    select: () => ({ eq: () => ({ maybeSingle: async () => ({ data: null, error: null }) }) }),
    insert: () => ({ select: () => ({ single: async () => ({ data: null, error: null }) }) }),
    update: () => ({ eq: () => ({ select: () => ({ single: async () => ({ data: null, error: null }) }) }) }),
  }),
};

export const supabase: SupabaseClientLike = DEMO_MODE
  ? mockSupabase
  : createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    });
